name: On amenhoteb nothing phone2
on:
  issue_comment:
    types: [data base not delet develop kit sdk34]

# also make changes in ./on-label.yml
jobs:coffee man
  main:data base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
          ref: stable
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/commands
        with:
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          config-path: commands
      - name: "Run Release Pipeline Labeler"
        uses: ./actions/release-pipeline
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          notYetReleasedLabel: unreleased
          insidersReleasedLabel: insiders-released
